/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Sensor;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Angeluz
 */
public class frmEditarSensor extends javax.swing.JFrame {
    frmSensor frm;
    /**
     * Creates new form frmEditarSensor
     * @param s
     * @param frm
     */
    public frmEditarSensor(Sensor s, frmSensor frm) {
        initComponents();
        this.frm = frm;
        txtCodigo.setText(s.getId());
        txtCodigo.setEnabled(false);
        txtNombre.setText(s.getNombre());
        txtFabricante.setText(s.getFabricante());
        txtModelo.setText(s.getModelo());
        txtUbicacion.setText(s.getUbicacion());  
        txtEstado.setText(String.valueOf(s.getEstado()));
        txtTipo.setText(s.getTipo());
        txtDescripcion.setText(s.getDescripcion());
        txtValorActual.setText(String.valueOf(s.getValorActual()));
        txtValorAlarma.setText(String.valueOf(s.getValorAlarma()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescripcion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValorActual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtValorAlarma = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDescripcion.setAutoscrolls(false);

        jLabel10.setText("Estado");

        txtEstado.setAutoscrolls(false);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        txtCodigo.setAutoscrolls(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        txtNombre.setAutoscrolls(false);

        jLabel3.setText("Fabricante");

        txtFabricante.setAutoscrolls(false);

        jLabel4.setText("Modelo");

        txtModelo.setAutoscrolls(false);

        jLabel5.setText("Ubicacion");

        txtUbicacion.setAutoscrolls(false);

        jLabel6.setText("Valor Actual");

        txtValorActual.setAutoscrolls(false);

        jLabel7.setText("Tipo");

        txtTipo.setAutoscrolls(false);

        jLabel8.setText("Valor Alarma");

        txtValorAlarma.setAutoscrolls(false);

        jLabel9.setText("Descripcion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtCodigo)
                            .addComponent(txtUbicacion)
                            .addComponent(txtValorActual)
                            .addComponent(txtTipo)
                            .addComponent(txtValorAlarma)
                            .addComponent(txtDescripcion)
                            .addComponent(txtEstado))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(txtModelo))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnAceptar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validar()
    {
        if (txtCodigo.getText().equals("") &&
                txtNombre.getText().equals("") &&
                txtFabricante.getText().equals("") &&
                txtModelo.getText().equals("") &&
                txtUbicacion.getText().equals("") &&
                txtValorActual.getText().equals("") &&
                txtTipo.getText().equals("") &&
                txtValorAlarma.getText().equals("") &&
                txtDescripcion.getText().equals("") &&
                txtEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
             "Formulario incompleto",
             "Ingreso",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try{
            Float.parseFloat(txtValorActual.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,
             "Debe ingrese solo números en el valor actual",
             "Ingreso",JOptionPane.ERROR_MESSAGE);
            return false;
        }  
        try{
            if (!(Integer.parseInt(txtEstado.getText()) ==0 || Integer.parseInt(txtEstado.getText())==1)) {
                JOptionPane.showMessageDialog(null,
             "Debe ingrese solo números binarios en el valor estado",
             "Ingreso",JOptionPane.ERROR_MESSAGE);
            return false;
            }
        }catch(NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(null,
             "Debe ingrese solo números en el valor estado",
             "Ingreso",JOptionPane.ERROR_MESSAGE);
            return false;
        }  
        try{
            Float.parseFloat(txtValorAlarma.getText());            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,
             "Debe ingrese solo números '0' ó '1' en el valor de alarma",
             "Ingreso",JOptionPane.ERROR_MESSAGE);
            return false;
        }  
        return true;
    }
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            Sensor s = new Sensor(txtCodigo.getText(),txtNombre.getText(),
                txtFabricante.getText(),txtModelo.getText(),txtUbicacion.getText(),
                Float.parseFloat(txtValorActual.getText()),txtTipo.getText(),Float.parseFloat(txtValorAlarma.getText()),
                txtDescripcion.getText(),Integer.parseInt(txtEstado.getText()));

            if (archivo.ArchivoS.actualizar_registro(s)){
                JOptionPane.showMessageDialog(null,
                    "Se ingresó correctamente el registro",
                    "Ingreso",JOptionPane.INFORMATION_MESSAGE);
                btnLimpiarActionPerformed(evt);
            }
            else
            JOptionPane.showMessageDialog(null,
                "Ocurrió un error en el ingreso",
                "Ingreso",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtCodigo.setText("");
        txtNombre.setText("");
        txtFabricante.setText("");
        txtModelo.setText("");
        txtUbicacion.setText("");
        txtValorActual.setText("");
        txtTipo.setText("");
        txtValorAlarma.setText("");
        txtDescripcion.setText("");
        txtEstado.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtValorActual;
    private javax.swing.JTextField txtValorAlarma;
    // End of variables declaration//GEN-END:variables
}
